### ISSUE TITLE
log4j Override?

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/alfresco-support-tools#33] opened 2016-11-11 17:26 UTC
Support Tools provides a log4j.properties file that includes (below). As a result of this, alfresco.log is "driven by" support tools log4j. Commenting this out results in default repo log4j.properties being used initially then writing to a log stops. 
Can you explain how this is expected to work, etc? It is causing confusion for customer who has Support Tools module installed.

log4j.appender.File=org.apache.log4j.DailyRollingFileAppender
log4j.appender.File.File=alfresco.log
log4j.appender.File.Append=true
log4j.appender.File.DatePattern='.'yyyy-MM-dd
log4j.appender.File.layout=org.apache.log4j.PatternLayout
log4j.appender.File.layout.ConversionPattern=%d{ABSOLUTE} %-5p [%c] %m%n

**Comment by AntonioSoler** [comment] 2016-11-15 13:04
On early versions I used to override the main log4.properties to put there the JMXlogger appender and configure its pattern, on later versions (1.7 and above I think) we moved the appender definitions to an extended log4.properties file, but you need to keep in mind that the 

log4j.rootLogger=error, Console, File

dictates where the events are logged.

The extended version of the log4j.properties is on:

{alfresco}\tomcat\webapps\alfresco\WEB-INF\classes\alfresco\module\AdminConsoleSupportTools\log4j.properties

**Comment by AntonioSoler** [comment] 2016-12-14 12:28
duplicate of #34

**Closed by AntonioSoler** 2016-12-14 12:28 UTC
