### ISSUE TITLE
Problem with active user sessions in french (version 1.8)

### ISSUE THREAD

**Issue by lcabaceira** [Alfresco/alfresco-support-tools#19] opened 2015-11-11 10:26 UTC
I've introduced  support tools to our Alfresco customer "Swiss federal court" and they liked it  :).
They are facing a problem while accessing the active sessions, may be related from their browser being in French.

This is the error output.

Exception:	freemarker.core.InvalidReferenceException - Expression user is undefined on line 56, column 67 in org/alfresco/enterprise/repository/admin/support-tools/admin-activesessions.get.html.ftl.

**Comment by AntonioSoler** [comment] 2015-11-11 14:04
looks like a duplicate of https://github.com/Alfresco/alfresco-support-tools/issues/16

**Comment by AntonioSoler** [comment] 2016-02-12 12:52
same as #21 , fixed with ef1f0ba

**Closed** 2016-02-12 12:53 UTC
